### ISSUE TITLE
Remove mentions of my name from your website, cease further use of my name.

### ISSUE THREAD

**Issue by ubernostrum** [tip4commit/tip4commit#146]
Currently the tip logs of your website list my name as a tip recipient. Your use of my name in tip logs creates the possibility of third parties incorrectly inferring that I have accepted or might accept such tips, or that I have some financial or other relationship with your site/"service", or that I in some way support, endorse or approve of your site/"service".
- I have not accepted any tips from your "service", nor do I ever plan to.
- I do not have any financial or other relationship with your site or "service".
- I have never requested nor consented to your "service". I do not in any way support, endorse or approve of your site or "service".

Remove mentions of my name from your website. Cease further use of my name on your website or in any other manifestation of your "service" or its promotion.

As it may be the case that this requires the addition of missing features in the codebase of your website and/or "service", I am prepared to grant a reasonable time in which to satisfy this request, provided that you display a good-faith effort to do so.

**Comment by Lvl4Sword** [comment]
> @apollo13 My mistake, sorry. I don't see you in the log, perhaps you opened a cached version? Anyway, deleted your info from our database.

I too would like my information removed, considering we can't do this ourselves ( https://github.com/tip4commit/tip4commit/issues/327 , https://github.com/tip4commit/tip4commit/issues/326 )

**Comment by alexandrz** [comment]
@Lvl4Sword I was going to remove your user as I could not find time to implement this feature, but I can not find the user in the database.

**Comment by Lvl4Sword** [comment]
@alexandrz Lvl4Sword, and ``users`` ID is 9668

**Comment by alexandrz** [comment]
@Lvl4Sword user deleted

**Comment by alexandrz** [comment]
I am closing this issue, as it's now possible to delete accounts using a form on the profile page.
