### ISSUE TITLE
Kill tip4commit

### ISSUE THREAD

**Issue by arsenische** [tip4commit/tip4commit#157]
Tip4Commit was created as a Rails Rumble 2013: http://r13.railsrumble.com/entries/410-tip4commit , it took about 48 hours and was fun. We didn't intend it to be our main project (and it is not), thought of it more of as community-driven project. So if community doesn't like it - we should kill it.

Initially Tip4Commit received mixed feedback at https://news.ycombinator.com/item?id=6916751 . But recently we received a lot of negative feedback. See https://news.ycombinator.com/item?id=8542969,  #127 and the linked tickets.

If community wants to close Tip4Commit - we should identify this situation and find a proper way to close it so that nobody is offended and we don't profit from it.

Please see https://github.com/tip4commit/tip4commit/wiki/FAQ before commenting.

**Comment by dennisvandehoef** [comment]
I beleve this can be closed now

**Comment by randrews-gbg** [comment]
Dunno why, you still haven't killed it.

**Comment by dennisvandehoef** [comment]
My Personal oppinion, it does not have to be killed.

And wenn it was the intent of the creators, it would have happend by now.
Since @arsenische added issue #197 (the next logical step: decentralize tip4commit) after this issue, wich also points in teh direction he changed his mind.

**Comment by randrews** [comment]
And I notice you still haven't done that; the main site is still taking donations.

Do whatever you like, to me it's obvious the whole thing is a scam but I haven't been able to get Github to care.

**Comment by mason-bially** [comment]
They seemed to at least have fixed the legal ramifications I was talking about, [this is what happens](https://tip4commit.com/projects/search?utf8=%E2%9C%93&query=mason-bially%2Fopenid-cas-bridge&order=balance) when you search for my non-commercial licensed repository. So I would vote for closing it.

:+1

**Comment by csvan** [comment]
Since most of the major issues are solved now, shouldn't this be closed?

**Comment by Lvl4Sword** [comment]
I don't suggest ceasing the project, but it would be wise to be able to delete accounts ( #327 ) or change the e-mail on your account. ( #326 )

**Comment by Lvl4Sword** [comment]
Being able to delete accounts should be top priority, as under GDPR this is a huge issue for anyone in the EU. +1 for ceasing the project. If this can't/won't be done, give us the ability to delete our own accounts.

**Comment by alimony** [comment]
You're most likely breaking the law by not allowing people to delete their accounts on your website, do you really want to wait until you receive a formal GDPR request you won't be able to fulfil?

**Comment by alexandrz** [comment]
@alimony We do allow deleting user accounts, and we did it several times. Unfortunately it can only be done via opening an issue on github for now, but it's planned to allow it via website's ui.

**Comment by alimony** [comment]
@alexandrz How do I delete my account and why is there no info about this on the website?

**Comment by alexandrz** [comment]
@alimony you just need to ask for it on github. If you wish it can deleted it now.

**Comment by alimony** [comment]
@alexandrz Yes please.

**Comment by alexandrz** [comment]
@alimony deleted
