### ISSUE TITLE
Please remove mplewis/*

### ISSUE THREAD

**Issue by mplewis** [tip4commit/tip4commit#158]
I don't want visitors to tip4commit to be able to donate to any of my projects via your site. Thanks!

**Comment by dennisvandehoef** [comment]
I belive this can be closed,does ot need to be open wenn waiting for his reaction.
When @mplewis responses it will be reopend.

**Comment by mplewis** [comment]
Could you please send the remaining balance to the following address:

`1JwTztpwonN9zSrUeMJs2Uxxe5C2bLBRV2`

Thanks!

**Comment by alexandrz** [comment]
@mplewis sent. sorry for the delay
