### ISSUE TITLE
Please remove IPython from any mention on your site

### ISSUE THREAD

**Issue by fperez** [tip4commit/tip4commit#175]
Please remove immediately the [IPython project](https://tip4commit.com/github/ipython/ipython) from any mention on your site. We do not endorse the use of the IPython project name on your site in any way, shape or form.

Nobody from the project maintainers team ever consented to be listed on your service. Please remove it immediately.

**Comment by dennisvandehoef** [comment]
I belive this can be closed, since it's on the black list
