### ISSUE TITLE
Federal fraud 

### ISSUE THREAD

**Issue by galori** [tip4commit/tip4commit#186]
This is fraud and can qualify for a FEDERAL consumer fraud lawsuit because unauthorized inter-state currency transfer is in play.

Relevant statutes:

http://www.lawyersandsettlements.com/lawsuits-filed/consumer-fraud-lawsuits/#.VF7JS4o76JI

http://criminal-law.freeadvice.com/criminal-law/white_collar_crimes/lawsuit_fraud.htm

**Comment by dennisvandehoef** [comment]
I beleve this can be closed now
