### ISSUE TITLE
Projects are being created without bitcoin address

### ISSUE THREAD

**Issue by arsenische** [tip4commit/tip4commit#190]
We have discovered recently that there are many projects in the database without a bitcoin address (e. g. https://tip4commit.com/projects/4000).

Probably the reason is that blockchain.info has limitations on amount of bitcoin addresses in a single wallet.

Anyway, this situation should be handled in our code correctly. Instead of creating and showing a project without a bitcoin address, a proper error message should be shown upon project creation attempt.

**Comment by alexandrz** [comment]
Fixed
