### ISSUE TITLE
Please remove all digipost repos

### ISSUE THREAD

**Issue by steinim** [tip4commit/tip4commit#218]
digipost/digipost-api-client-java
digipost/ios
digipost/printability-validator
digipost/Digipost-Chrome-plugin-for-ende-til-ende-krypto
digipost/labs
digipost/sdp-shared
digipost/android
digipost/stax-ex
digipost/Android-Pdf
digipost/Android-Push
digipost/sdp-error-handling
digipost/digipost-open-super-pom

**Comment by alexandrz** [comment]
I can't find any of these repos at t4c.
