### ISSUE TITLE
please add 'electrum' project

### ISSUE THREAD

**Issue by Perlover** [tip4commit/tip4commit#236]
Hello,

I am not author of this prokect but i think this project should be added :)

https://github.com/spesmilo/electrum

**Comment by alexandrz** [comment]
It would be better to ask the owner. ;)

**Comment by Perlover** [comment]
OK :)
I will send this link to him

**Comment by alexandrz** [comment]
It would be better to ask the owner. ;)

**Comment by alexandrz** [comment]
Hi, I've added it: https://tip4commit.com/github/spesmilo/electrum
