### ISSUE TITLE
empty address for a recently added project

### ISSUE THREAD

**Issue by llazzaro** [tip4commit/tip4commit#239]
Hi,

recently it was added this project https://tip4commit.com/github/llazzaro/analyzer, however the qr code value si "bitcoin:"

thanks

**Comment by alexandrz** [comment]
@arsenische Could you please check this? Something wrong with Blockchain API I guess.

**Comment by alexandrz** [comment]
@llazzaro Fixed it. Sorry for the delay. Our blockchain.info wallet is too big now, it's not possible to generate new addresses. Only today I realized that we can reuse addresses from removed projects.
