### ISSUE TITLE
Add GeekEngine project

### ISSUE THREAD

**Issue by dmcclccam** [tip4commit/tip4commit#243]
Hello there,

I'm developing a fork of brackets intending to be a code editor fully integrated with Steam (achievements, bagdes etc), so it you be great to have tip4commit integrations, as it'll pay not only me (the core developer) but anyone willing to help coding.

[GeekEngine/geekengine](https://github.com/GeekEngine/geekengine)

Best regards,
Danilo Castro

**Comment by alexandrz** [comment]
Added it: https://tip4commit.com/github/GeekEngine/geekengine

**Comment by dmcclccam** [comment]
Thanks!
