### ISSUE TITLE
Many Issues not being marked as solved

### ISSUE THREAD

**Issue by johnathanmartin** [tip4commit/tip4commit#249]
After an issue is solved it should be marked as such to clear everything up. This will make it easier to see what needs to be done and what is done.

Below I have included ALL of the issues that should be marked as solved:

#245 
#239 
#202 
#186 
#175 
#158 
#155 
#154 
#147 
#66 

PLEASE, Please mark these as solved. I can provide a reason why everyone of those should be solved if you are unsure. Thank You!

**Comment by alexandrz** [comment]
Closed most of them. Thank you.
