### ISSUE TITLE
NodeBB/nodebb-plugin-composer-redactor

### ISSUE THREAD

**Issue by drewdotpro** [tip4commit/tip4commit#255]
https://github.com/NodeBB/nodebb-plugin-composer-redactor
to be added please.

Proof I'm a project maintainer:
https://github.com/orgs/NodeBB/people

Thanks.

**Comment by alexandrz** [comment]
Added https://tip4commit.com/github/NodeBB/nodebb-plugin-composer-redactor Sorry for the delay!
