### ISSUE TITLE
[Support] 3 projects funded with a total of BTC 4.5, transactions visible on blockchain, balances never reflected on tip4commit, money moved out of projects wallets.

### ISSUE THREAD

**Issue by gubatron** [tip4commit/tip4commit#261]
Not sure where else to file this, tried reaching over twitter.

Hi there, on September 4, I tried to send the donations of our users to fund the following 3 repositories to keep driving development. But the deposits were never shown, and we can see the funds have been taken out of the accounts. We don't know the internals of how tip4commit taps into the wallets, but this makes us think that either the project's wallet's have been compromised and someone stole the bitcoins, or tip4commit has a bug that should be fixed and our project's balances should reflect this.

The projects funded on 09/04/2015 were the following:

# frostwire-android (BTC 2.0)
https://tip4commit.com/github/frostwire/frostwire-android
[Deposited BTC 2.0](https://blockchain.info/tx/30b64c4f085498af890194db13d03bc98c5bb40eb0f9d77357e9b62b2af9f603) to [12cNbY9yotLZvs5cfrhj7sBMTaLZaBP5HP](https://blockchain.info/address/12cNbY9yotLZvs5cfrhj7sBMTaLZaBP5HP)

yet the last deposit shown on tip4commit is from 25 Jul and all the tips after 09/04/2015 are still 1% of the old balance, and then on 09/09/2015 BTC 1.99 [left the wallet](https://blockchain.info/tx/7aca9093b7818bd2b4d246df6c173cf0a0b8b4ec7558d292c3dadff52ca87137), to [who](https://blockchain.info/address/1HzRcds2rubVbSfXAvGS43fuEoeGzaH4g4)??? **super3/peercoin.net**?

![screen shot 2015-09-11 at 9 54 40 am](https://cloud.githubusercontent.com/assets/163977/9816468/37b0d9fc-586b-11e5-9574-4958e526bd48.png)

# frostwire-jlibtorrent (BTC 1.5)
https://tip4commit.com/github/frostwire/frostwire-jlibtorrent
[Deposited BTC 1.5](https://blockchain.info/tx/32e6ce2b0f6abb6f9c58152a53f4a003e29001cd7dba50a50f64755c8a8c4764) to [1L1pRzY7TpbPe7Hz37x8JYodhjssVJtsUS](https://blockchain.info/address/1L1pRzY7TpbPe7Hz37x8JYodhjssVJtsUS)
In this case the money seems to still be there on the wallet, but again, the Balance on tip4commit is not being reflected.

# frostwire-desktop (BTC 1)
https://tip4commit.com/github/frostwire/frostwire-desktop
[Deposited BTC 1](https://blockchain.info/tx/0cc7500f15448e40b805391fca6830bc8f6ce78517c20713e3c65092925ea228) to [1vmWNkp9SPxj4EoJ1mbs1bhQGQCwMf9qd](https://blockchain.info/address/1vmWNkp9SPxj4EoJ1mbs1bhQGQCwMf9qd)

Please help us, we don't know if your system is just lagging, or if the wallets have been compromised, but we think this is a serious problem that demands your attention.

My email is gubatron@gmail.com if you want to take this conversation elsewhere.

**Comment by arsenische** [comment]
Thanks for reporting, please don't worry, the funds are in Tip4Commit's wallet. It looks like a technical issue with blockchain.info callbacks.

**Comment by gubatron** [comment]
thank you so much @arsenische

**Comment by alexandrz** [comment]
Created all missing deposits manually. Sorry for inconvenience. Will investigate what has happened to blockchain api.

**Comment by gubatron** [comment]
Thank you so much! Problem solved.
