### ISSUE TITLE
Zero balance in interface 

### ISSUE THREAD

**Issue by aluminiumgeek** [tip4commit/tip4commit#268]
Well, https://tip4commit.com/github/aluminiumgeek/cc-telegram shows zero balance, but according to blockchain.info there's at least one transaction on donation address: 
https://blockchain.info/address/1NVvnsEZXCmH1X2GDmLXqZR6oo1DtJirHc

**Comment by alexandrz** [comment]
We are having issues with blockchain api. I am temporarily adding new deposits manually. Don't worry, the transaction is not lost I can see it in the wallet. Sorry for the delay.

**Comment by aluminiumgeek** [comment]
Any updates?

**Comment by alexandrz** [comment]
@aluminiumgeek Sorry for the delay, I was busy during the week. I've created the deposit and you can see your project's balance updated.

For some reason I don't see this address in the tip4commit wallet and I had to change it to another one `14E3DTdUzsPqc4fL2fL1JNifAqYpmw2sjE` please, don't use the older address. I will contact blockchain info and ask what might happen. Likely that address was archived a year ago, when the wallet ran out of addresses. (there is a limit of 1000 addresses we hadn't known about)
