### ISSUE TITLE
Adding https://github.com/binary-com/webtrader

### ISSUE THREAD

**Issue by jy-binary** [tip4commit/tip4commit#270]
We would wish to add the https://github.com/binary-com/webtrader project.

Best regards
Jean-Yves Sireau
CEO, Binary.com

**Comment by alexandrz** [comment]
I'll add it during the weekend after migrating to the new wallet.

**Comment by alexandrz** [comment]
Added it: https://tip4commit.com/github/binary-com/webtrader please, sorry for the delay.
