### ISSUE TITLE
New FrostWire Monorepo Repository.

### ISSUE THREAD

**Issue by frostwire** [tip4commit/tip4commit#276]
Hello, my name is [Angel Leon](https://onename.com/gubatron), founder and developer of FrostWire.

I need your help @tip4commit as we'll be phasing out 3 of our projects and replacing them for a single one.

We're moving our [frostwire/frostwire-desktop](https://github.com/frostwire/frostwire-desktop), [frostwire/frostwire-android](https://github.com/frostwire/frostwire-android), and [frostwire/frostwire-common](https://github.com/frostwire/frostwire-common) into a single repository hosted at [frostwire/frostwire](https://github.com/frostwire/frostwire) (we've even left a note on the read me)

There's still some balance left on these 3 projects that'd we'd like to move over, but we see that it's no longer possible to add new projects, or somehow manage the existing projects. 

Not sure what is the procedure is:

a) Moving remaining balances to new frostwire/frostwire project on tip4commit, then deleting old projects from tip4commit.
b) Making a [refund to the FrostWire donations wallet](http://frostwire.com/bitcoin), adding new project frostwire/frostwire on tip4commit, then we fund new project.

**Comment by alexandrz** [comment]
Added new project https://tip4commit.com/github/frostwire/frostwire
