### ISSUE TITLE
Upgrade to rails 4.2

### ISSUE THREAD

**Issue by narutosanjiv** [tip4commit/tip4commit#278]
@alexandrz Will it be fine to upgrade ruby & rails?. Later on we can upgrade twitter-bootstrap to latest versions?. What is your thoughts on this?. I will upgrade both part.

**Comment by alexandrz** [comment]
Sure, let's do it!

**Comment by narutosanjiv** [comment]
Ok, i am working on it.

**Comment by narutosanjiv** [comment]
Upgraded rails to latest & Now will work on upgrading twitter bootstrap
