### ISSUE TITLE
Please add: nicolasgramlich/AndEngine

### ISSUE THREAD

**Issue by nicolasgramlich** [tip4commit/tip4commit#290]
https://github.com/nicolasgramlich/AndEngine

**Comment by alexandrz** [comment]
Added it https://tip4commit.com/github/nicolasgramlich/AndEngine

Please, sorry for the delay. I wanted to migrate tip4commit to a new wallet, but blockchain.info hasn't fixed the issue preventing me from finishing it. I am still processing deposits manually, so expect delays up to 2 weeks.
