### ISSUE TITLE
Add 'nomic' project

### ISSUE THREAD

**Issue by mburns** [tip4commit/tip4commit#295]
I'd like to add https://github.com/mburns/nomic to tip4commit.

Nomic is a game where the decisions and player-actions are carried out by participating in pull requests, issues and commits.

**Comment by alexandrz** [comment]
Added it https://tip4commit.com/github/mburns/nomic

Sorry for the delay. I wanted to migrate tip4commit to a new wallet api and add new project after finishing this, but blockchain info hasn't fixed the issue that prevented me from doing this. I am still processing new deposits manually which can take up to 2 weeks.
