### ISSUE TITLE
Add way to filter by programming language

### ISSUE THREAD

**Issue by APerson241** [tip4commit/tip4commit#297]
While viewing the list of all of the projects, it should be possible to display only those projects that are at least partially written in a specified programming language.

I was thinking something like a Chosen multiselect.

**Comment by sytolk** [comment]
:+1:

**Comment by alexandrz** [comment]
You can actually search with language name now: https://tip4commit.com/projects/search?utf8=%E2%9C%93&query=ruby&order=balance

**Comment by APerson241** [comment]
Well, I didn't know that, so I opened #299.

But obviously this capability exists, so closing.
