### ISSUE TITLE
Add my project

### ISSUE THREAD

**Issue by sytolk** [tip4commit/tip4commit#298]
I like the idea tip for commit and can contribute to supported projects. 

What is the requirements? and can you add my project: https://github.com/sytolk/TaxiAndroidOpen

Thanks.

**Comment by alexandrz** [comment]
Added https://tip4commit.com/github/sytolk/TaxiAndroidOpen

The only requirement is project maintainers have to agree with adding the project.

Sorry it took so long to add it. I hoped to migrate tip4commit to a new wallet, but blockchain.info hasn't fixed the issue preventing me from finishing it. I am still processing deposits manually, so expect delays up to 2 weeks.
