### ISSUE TITLE
missing donation

### ISSUE THREAD

**Issue by jl777** [tip4commit/tip4commit#301]
I made a donation for jl777/SuperNET but it did not appear after a couple days

b00b971f97f622daace22fad3e8de11fafca470dc2c8b982c47b11dfb62c6a31

**Comment by alexandrz** [comment]
Processed it. Please, sorry for the delay. Blockchain receiving api we were using is broken now and I have to process deposits manually until we find a way of fixing it.

**Comment by jl777** [comment]
thanks! please let me know here when things are automated again. I will delay publicising the link until it wont cause issues

**Comment by alexandrz** [comment]
Thank you for motivating me :) I am testing a new solution now, deposits are being created automatically, but not instantly.
