### ISSUE TITLE
Please add project "Talksy"

### ISSUE THREAD

**Issue by blacksector** [tip4commit/tip4commit#303]
Hello! Would be really kind of you to possibly add my new project to your list: https://github.com/blacksector/talksy-android/

Thanks!

**Comment by alexandrz** [comment]
Is this project still alive and needs to be added? Sorry for not doing this when you requested, I was planning to allow maintainers to add projects themselves, but could find enough time to do it.

**Comment by blacksector** [comment]
Unfortunately no longer maintained. I may in the future but at the moment, no. Thank you though :)
