### ISSUE TITLE
Remove Syncthing-Android

### ISSUE THREAD

**Issue by Nutomic** [tip4commit/tip4commit#304]
Can you please remove [syncthing-android](https://tip4commit.com/github/syncthing/syncthing-android) from tip4commit? The remaining balance should go to this Bitcoin address:

1DPZfuMd1o6ryUkQd2ZfYjz4z6kgueqYey

This has nothing to do with tip4commit, I request this only because we have a common donation method for all Syncthing projects [here](https://syncthing.net/#donate). The address above belongs to me, and I will transfer the funds to the Syncthing donations pool as soon as I get them.

**Comment by alexandrz** [comment]
Removed

**Comment by Nutomic** [comment]
Thank you :)
