### ISSUE TITLE
secret-ethereum-login/Wherewewere

### ISSUE THREAD

**Issue by secret-ethereum-login** [tip4commit/tip4commit#307]
secret-ethereum-login/Wherewewere would like to use Tip4Commit please!

**Comment by alexandrz** [comment]
Is this project still alive and needs to be added? Sorry for not adding it when you requested, I wanted to allow maintainers to add projects, but could find time to finish this feature.

**Comment by secret-ethereum-login** [comment]
Naw, thanks!
