### ISSUE TITLE
Add these Emercoin projects please

### ISSUE THREAD

**Issue by vx28643** [tip4commit/tip4commit#308]
Add these 2 Emercoin projects please

https://github.com/Emercoin/emercoin
https://github.com/Emercoin/emcweb

The request has been approved by the project's maintainer. Please reply or close issue when added - so I know to add some tips! 

Thank you!

**Comment by alexandrz** [comment]
Added:

https://tip4commit.com/github/Emercoin/emercoin
https://tip4commit.com/github/Emercoin/emcweb

Please, sorry for the delay. I hope it's not too late. I was planning to allow maintainers to add projects by themselves, but could not find enough time to finish this feature.
