### ISSUE TITLE
Please add aquapilot project I need help to achieve this great project for aquariums

### ISSUE THREAD

**Issue by sebastienvermeille** [tip4commit/tip4commit#322]
http://www.aquapilot.org/

Project: An open-source monitor for aquaponists and hydroponists. Help you to manage your aquarium and garden. And when something need your intervention you get notified.

Repository:
https://github.com/aquapilot/aquabox

Thank you very much

**Comment by alexandrz** [comment]
Added https://tip4commit.com/github/aquapilot/aquabox

Sorry for the delay
