### ISSUE TITLE
Ability to delete account

### ISSUE THREAD

**Issue by Lvl4Sword** [tip4commit/tip4commit#327]
Having accounts floating around the internet isn't a very good idea. This is a huge issue under GDPR and anyone on the site within the EU.

**Comment by alexandrz** [comment]
@Lvl4Sword I will do it, but could you please explain me what is wrong with mirroring commiter information that is publicly available on github? Why is not it good idea? The table is called `users`, but the records are not necessary accounts nor real users of tip4commit.

**Comment by Lvl4Sword** [comment]
``could you please explain me what is wrong with mirroring commiter information that is publicly available on github?``
That isn't what I raised. I want the ability to delete an account on tip4commit.
If you have any question about anything on GitHub, you may want to discuss it with the GitHub team.

**Comment by alexandrz** [comment]
It's possible now to delete your account now.
