### ISSUE TITLE
when logging in with github: "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [tip4commit/tip4commit#332]
* happened to 2 users
* with https (https://tip4commit.com) and plain http
* tried with 2 browsers (FF + palemoon)

similar, closed reports: #293 #201

on request further info is available

**Comment by alexandrz** [comment]
@Erkan-Yilmaz could you please check it again. Should be fixed now.

**Comment by swapper3d** [comment]
It seems fixed now.
