### ISSUE TITLE
TLS cert error on https://tip4commit.com/

### ISSUE THREAD

**Issue by JeremyRand** [tip4commit/tip4commit#339]
> tip4commit.com uses an invalid security certificate.
> 
> The certificate is only valid for the following names:
> sni117692.cloudflaressl.com, *.11question.pw, *.rongl.info, 11question.pw, rongl.info
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

This is in Tor Browser (I've tried switching Tor circuits).  Any idea what might be wrong?

**Comment by jonathancross** [comment]
I'm seeing the same form US and Swiss IP addresses.  Sometimes it returns a server error:
> 403 Forbidden
> cloudflare-nginx

**Comment by alexandrz** [comment]
Thank you for reporting the issue. Seems like cloudfare stopped supporting expired certificates without saying anything. I will get a new one and try to fix it during the weekend.

**Comment by alexandrz** [comment]
Waiting when cloudflare's support fixes our certificate. The isssue is https://community.cloudflare.com/t/cloudflare-serving-wrong-ssl-certificate/1021/19

**Comment by alexandrz** [comment]
Fixed
