### ISSUE TITLE
Please reassign some funds to different repos

### ISSUE THREAD

**Issue by JeremyRand** [tip4commit/tip4commit#342]
Hi!  At Namecoin, we've deprecated some old repos in favor of some newer repos, and we'd like the Tip4Commit funds that are currently assigned to the deprecated repos (which will likely never get new commits) to be reassigned to the corresponding new repos.

Please reassign as follows:

* https://github.com/namecoin/nmcontrol : please reassign, split evenly between https://github.com/namecoin/ncdns and https://github.com/namecoin/ncdns-nsis
* https://github.com/namecoin/Convergence : please reassign, split evenly between https://github.com/namecoin/ncdns , https://github.com/namecoin/ncdns-nsis , and https://github.com/namecoin/dns-prop279
* https://github.com/namecoin/libcoin : please reassign, split evenly between https://github.com/namecoin/namecoin-core , https://github.com/namecoin/electrum-nmc , https://github.com/namecoin/electrumx , https://github.com/namecoin/libdohj , and https://github.com/namecoin/consensusj
* https://github.com/namecoin/namecoin-legacy : please reassign to https://github.com/namecoin/namecoin-core

Thanks!

**Comment by alexandrz** [comment]
reassigned – https://tip4commit.com/projects/search?utf8=%E2%9C%93&query=namecoin&order=balance

**Comment by JeremyRand** [comment]
Thanks.
