### ISSUE TITLE
Add DragonFly BSD project

### ISSUE THREAD

**Issue by tuxillo** [tip4commit/tip4commit#344]
Hi,

Can you please let me know what is the procedure to add www.dragonflybsd.org to tip4commit?

Regards,
Antonio Huete

**Comment by alexandrz** [comment]
Only mainainers can add their projects now.

**Comment by tuxillo** [comment]
Hi,

Maintainers of what? Of the project to be added?

Regards,
Antonio Huete

**Comment by alexandrz** [comment]
yes

**Comment by tuxillo** [comment]
Well, I am part of the project, what proof do you need?

**Comment by tuxillo** [comment]
So what's needed for this project to be added? Can you please share?

**Comment by alexandrz** [comment]
What is the github url of the project?

**Comment by tuxillo** [comment]
Our project is mirrored in github: https://github.com/DragonFlyBSD/DragonFlyBSD

But the original repository is self hosted: https://www.dragonflybsd.org/download/#index3h2

Let me know if you need more information.

**Comment by alexandrz** [comment]
Added https://tip4commit.com/github/DragonFlyBSD/DragonFlyBSD
