### ISSUE TITLE
Add OpenVPN to list of supported projects

### ISSUE THREAD

**Issue by ordex** [tip4commit/tip4commit#345]
The OpenVPN project is currently missing from the list of supported projects and should probably be added.

**Comment by alexandrz** [comment]
Only project maintainers are able to add projects to tip4commit.

**Comment by ordex** [comment]
Sure, if you check on the OpenVPN project you can see me listed as owner. Is that enough? Or you need a different proof?

**Comment by alexandrz** [comment]
Yes, added https://tip4commit.com/github/OpenVPN/openvpn

**Comment by ordex** [comment]
Thanks!
