### ISSUE TITLE
Payouts?

### ISSUE THREAD

**Issue by Humzini** [tip4commit/tip4commit#367]
Balance has gone past the threshold, how does one get paid because on each project it says the funds are "waiting for withdrawal", but there does not seem a way to withdraw them as the profile page says you will automatically be paid when the balance is over the threshold but this doesn't seem to be happening. Would appreciate an answer and a solution as well.

**Comment by alexandrz** [comment]
Done – https://tradeblock.com/bitcoin/tx/d738f3b47ebe1701ddb90a8a2d072e8e35f736f532bc9932ba3ea5c981a97bbb
