### ISSUE TITLE
payout request

### ISSUE THREAD

**Issue by cr0** [tip4commit/tip4commit#402]
Hey guys, as far as I can see from the issues here, payouts are processed manually. Thus, can you please trigger a payout, thanks ;)

**Comment by kaue** [comment]
Yeah, looks like no one is getting withdraws since March 2020 (https://tip4commit.com/github/tip4commit%2Ftip4commit/tips)
@alexandrz are you still processing withdraws manually?

**Comment by dennisvandehoef** [comment]
Fun fact, as for tip4commit, it are all withdraws for @alexandrz 

Don't think that that is what @cr0 meant 😉

**Comment by alexandrz** [comment]
New withdrawal is processed – https://tradeblock.com/bitcoin/tx/6277cb094715bc4d86b4515962dc9a59b6eb7620eb755cbb1a69fd7671d6fddf

**Comment by cr0** [comment]
Great thank you

 

Von: Aleksandr Zykov <notifications@github.com> 
Gesendet: Sunday, 14 February 2021 21:26
An: tip4commit/tip4commit <tip4commit@noreply.github.com>
Cc: Christian Roth <christian.roth@port17.de>; Mention <mention@noreply.github.com>
Betreff: Re: [tip4commit/tip4commit] payout request (#402)

 

New withdrawal is processed – https://tradeblock.com/bitcoin/tx/6277cb094715bc4d86b4515962dc9a59b6eb7620eb755cbb1a69fd7671d6fddf
