### ISSUE TITLE
Withdrawal won't be processed

### ISSUE THREAD

**Issue by zootreeves** [tip4commit/tip4commit#410]
HI

The balance is higher than the withdrawal threshold, but the withdrawal is not being processed for more than 24 hours.

**Comment by alexandrz** [comment]
> HI
> 
> The balance is higher than the withdrawal threshold, but the withdrawal is not being processed for more than 24 hours.

Hi, this project belonged to Ben Reeves. Your account was created just 22 days ago. Can you prove that you are Ben Reeves? Probably you could send me DM from your twitter account.

**Comment by zootreeves** [comment]
as you might seen my twitter account has been suspended, and I have no way to log in
https://twitter.com/zootreeves

p.s 
so was my github account and I had to reacquire the old username, using github's name squatting policy

**Comment by alexandrz** [comment]
I don't see this twitter suspended.

Do you at least have access to your reddit account?

**Comment by zootreeves** [comment]
sadly no, as they were linked with the same email, to which I have lost access about a year ago
