### ISSUE TITLE
No withdrawal for months

### ISSUE THREAD

**Issue by blrhc** [tip4commit/tip4commit#440]
@sashazykov No withdrawals have been done for months, and commits are not being logged.

**Comment by sashazykov** [comment]
Hi, thank you for reporting commits logging issue. I fixed it. Regarding the withdrawals, the total amount of pending withdrawals was too low, but you are right it has been too long. I will initiate it when bitcoin network fees are a bit lower.

**Comment by sashazykov** [comment]
Hi, a new withdrawal was done today.
